apiVersion: v1
kind: Service
metadata:
  name: gamepulse-app-service
  labels:
    app: gamepulse-app
spec:
  selector:
    app: gamepulse-app
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP