apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gamepulse-dev
resources:
  - ../../base
images:
  - name: ghcr.io/gimmzee/gamepulse-app
    newTag: latest
  - name: ghcr.io/gimmzee/gamepulse-frontend
    newTag: sha-685a999